name: Checkmarx One Scan

# ↓ lock down top‐level permissions. Define all permissions at job level
permissions: {}

on:
  pull_request_target:  # Changed from pull_request to pull_request_target
    types: [opened, synchronize, reopened]
    branches: [ '**' ]
  push:
    branches: [ 'main' ]
  workflow_dispatch: {}   # so you can still run it manually
  schedule:
    - cron: "0 0 * * *"   # run daily at midnight UTC
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  build:
    permissions:
      contents: read             # we only need to checkout code
      actions: read              # to query workflows/runs
      pull-requests: write       # to comment on or label PRs
      security-events: write

    runs-on: ubuntu-latest

    steps:
      # CRITICAL: DO NOT CHECKOUT THE PR CODE
      # This is what makes it safe with pull_request_target

      - name: Checkmarx Full Scan
        uses: midnightntwrk/upload-sarif-github-action/checkmarx-scan-public@53cdf3148dbbd85518ecc5e8f1ec485852c99c36
        with:
          cx-client-id: ${{ secrets.CX_CLIENT_ID }}
          cx-client-secret: ${{ secrets.CX_CLIENT_SECRET_EU }}
          cx-tenant: ${{ secrets.CX_TENANT }}
          scs-repo-token: ${{ secrets.MIDNIGHTCI_REPO }}
          upload-to-github: 'true'
